# Generated by Django 2.1.4 on 2019-01-20 15:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=50)),
                ('purchased_date', models.DateTimeField(default=datetime.datetime(2019, 1, 20, 23, 11, 26, 994829))),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_consumer_id', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_vendor_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
