# Generated by Django 2.1.4 on 2018-12-21 09:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.CharField(default='', max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('vendor_status', models.CharField(default='NotAccepted', max_length=50)),
                ('consumer_status', models.CharField(default='NotPurchased', max_length=50)),
                ('purchased_date', models.DateTimeField(default=datetime.datetime(2018, 12, 21, 17, 12, 32, 398273))),
                ('accepted_date', models.DateTimeField(null=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_consumer_id', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_vendor_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
